# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jn0iy2pYWDRjNw_bG7PLVSaIRbavvDfG
"""

from fastapi import FastAPI
from pydantic import BaseModel
from inference import predict_fake_news

app = FastAPI()

class NewsInput(BaseModel):
    statement: str
    job: int
    party: int
    context: int

@app.post('/predict')
def predict(news: NewsInput):
    prediction, probabilities = predict_fake_news(
        news.statement, news.job, news.party, news.context
    )
    label = 'Fake' if prediction == 1 else 'Real'
    return {"label": label, "probabilities": probabilities.tolist()}