# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jn0iy2pYWDRjNw_bG7PLVSaIRbavvDfG
"""

import streamlit as st
import requests

st.title("Fake News Detector")

statement = st.text_area("Enter News Statement:")
job = st.number_input("Job ID:", min_value=0, step=1)
party = st.number_input("Party ID:", min_value=0, step=1)
context = st.number_input("Context ID:", min_value=0, step=1)

if st.button("Check Authenticity"):
    data = {
        "statement": statement,
        "job": job,
        "party": party,
        "context": context
    }
    response = requests.post("http://localhost:8000/predict", json=data)
    result = response.json()

    st.write(f"Prediction: **{result['label']}**")
    st.write(f"Confidence: {result['probabilities']}")